### ISSUE TITLE
Unable to run multi nested Query

### ISSUE THREAD

**Issue by kaumudpa** [isoos/elastic_client#1]
Unable to run a complicated query for example:

{
    "suggest": {
        "movie-suggest" : {
            "prefix" : "captain america the",
            "completion" : {
                "field" : "name.completion"
            }
        }
    }
}

Any idea how this can be achieved?

**Comment by isoos** [comment]
How would you do this with `curl`?

**Comment by kaumudpa** [comment]
on kibana shell

we use
`POST _search
{
    "suggest": {
        "movie-suggest" : {
            "prefix" : "cap",
            "completion" : {
                "field" : "name.completion"
            }
        }
    }
}'

**Comment by kaumudpa** [comment]
on kibana shell we use `POST _search
{
    "suggest": {
        "movie-suggest" : {
            "prefix" : "cap",
            "completion" : {
                "field" : "name.completion"
            }
        }
    }
}`

**Comment by kaumudpa** [comment]
here is another example

`POST _search
{
  "suggest": {
    "movie-suggest-fuzzy": {
      "prefix": "captain amerca the",
      "completion": {
        "field": "name.completion",
        "fuzzy": {
          "fuzziness": 1
        }
      }
    }
  }
}`

**Comment by kaumudpa** [comment]
> here is another example
> 
> `POST _search
{
  "suggest": {
    "movie-suggest-fuzzy": {
      "prefix": "captain amerca the",
      "completion": {
        "field": "name.completion",
        "fuzzy": {
          "fuzziness": 1
        }
      }
    }
  }
}`

This query supports fuzziness ( ability to get similar output  but this time with a typo captain "amrica the")

**Comment by isoos** [comment]
I see. Could you please also provide an example result set? I'm not actively using the `suggest` query, and the current `search()` method is using a top-level `query` object. If the format is the same, I'd probably massage this inside that method, otherwise this could go into a new method.

**Comment by kaumudpa** [comment]
This is what we are trying to implement.
This doc is exactly what we have on our elastic instance.
https://hackernoon.com/elasticsearch-building-autocomplete-functionality-494fcf81a7cf

Now if you want to test. You can query through cURL 
elastic : `35.238.250.118:9200`

The above mentioned link is working with demo data  and querying will give you the results.

Give it a try.

**Comment by isoos** [comment]
Looks like this is a better URL about the suggest queries:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

It needs a bit of coding to introduce an extension on both the search requests and response, not sure when it will be done, but I accept PRs.

**Comment by isoos** [comment]
I've released 0.1.1 with the support for suggest queries. I haven't done much testing with it, please let me know if they are useful/working.

**Comment by rafiqueud** [comment]
Maybe that PR can made the search method more dynamically functional:
https://github.com/isoos/elastic_client/pull/5

please take a look
