### ISSUE TITLE
Exception: Failed to search {terms: {companies.companyName: [data]}}

### ISSUE THREAD

**Issue by mayankjanmejay** [isoos/elastic_client#10]
Hello,
I was attempting to use your plug in but I cant seem to get it to work using your example as a guide.

var client = new elastic.Client(ConsoleHttpTransport(Uri.parse('http://35.198.171.246//elasticsearch/'), basicAuth: BasicAuth('user','******')) );

Then I built a test function 

   search()
   async {
                final rs2 = await client.search(

      'companies',

      'companies',

      elastic.Query.term('companies.companyName', ['data']),

      source: ['companies.companyName', 'companyName'],

      //sort: [{ "name" : "asc" }, { "name.keyword" : "asc" }]

    );
      print(rs2.toMap());
   }  

Then I am getting the following Error

E/flutter ( 4289): Exception: Failed to search {terms: {companies.companyName: [data]}}
E/flutter ( 4289): #0      Client.search 
package:elastic_client/src/elastic_client_impl.dart:127
E/flutter ( 4289): <asynchronous suspension>
E/flutter ( 4289): #1      _ClientSearchState.search 
package:GreenSFA/agentPages/searchClient.dart:389
E/flutter ( 4289): <asynchronous suspension>
E/flutter ( 4289): #2      _ClientSearchState.build

**Comment by isoos** [comment]
The exception happens when the elastic server responds with a non-200 HTTP response. Could you please check/debug what and why it responds with that?

**Comment by mayankjanmejay** [comment]
Hi, after correcting the link in Uri.Parse I was able to make some sort of connection but I keep getting a 404. 

> "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n"


`   async {
var client =new elastic.Client(ConsoleHttpTransport( Uri.parse("http://35.198.171.246/elasticsearch/"), basicAuth: BasicAuth('user','****')) );

final rs2 = await client.search(
      'items',
      'items',
      elastic.Query.term('items.name.keyword', ['PORC']),
      source  : true,
          );
      print(rs2.toMap());
   } `



I tried matchAll and I am still getting a 404
final rs2 = await client.search(
      'items',
      'items',
      elastic.Query.matchAll(),
      source  : true,
      //sort    : [ { "items.name" : "asc" }      , { "items.name.keyword" : "asc" }]
    );



**Is there something wrong in my elastic.Query?** 
I am also attaching a sample of my dataset.


Thank You :)


![data subset](https://user-images.githubusercontent.com/35850067/61459645-dd440100-a975-11e9-985e-445ad6c9874b.PNG)

**Comment by isoos** [comment]
Oh, I think I have a possible cause for your issue: your ElasticSearch instance is serving on a non-root context (`/elasticsearch` in the URL), and our HTTP transport does not preserve it. It should be easy to fix, but I might only have time for it only tomorrow or the weekend.

**Comment by mayankjanmejay** [comment]
I believe you are correct. This is how Google Cloud Platform default installs Elasticsearch, there may be some convoluted method of changing it but I am really unsure how. 

I cant thank you enough for your helping out with this issue!!

**Comment by isoos** [comment]
@mayankjanmejay I've published  `0.1.6`, can you take a look and see if it is working for you now?

**Comment by mayankjanmejay** [comment]
Your fix worked but there seems to be another line that might need your attention. 

elastic_client_impl.dart
Line 131
final int totalCount = (hitsMap['total'] as int) ?? 0;

Throws
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'int' in type cast

**Comment by isoos** [comment]
Could you please provide the server response for that?

**Comment by mayankjanmejay** [comment]
I made this change to your code and its working great!

final hitsMap = body['hits'] ?? const {};
    final totalMap=hitsMap['total'];
    final int totalCount = (totalMap['value'] as int) ?? 0;


![hitsMap](https://user-images.githubusercontent.com/35850067/61476498-e0e78000-a995-11e9-813b-f35cd83e52b7.PNG)

**Comment by isoos** [comment]
That indicates that the response structure is different, I'm wondering why that would be....

**Comment by mayankjanmejay** [comment]
I changed the query type the server response was the same. Would you like me to connect to Elastic Cloud Hosting and see if I get a different response?

**Comment by mayankjanmejay** [comment]
![image](https://user-images.githubusercontent.com/35850067/61477235-733c5380-a997-11e9-9018-e71f0dc31da0.png)

This is the response I get from a elastic instance on cloud.elastic.co

**Comment by mayankjanmejay** [comment]
I have a question, using your plug in how can I make a prefix query 

"prefix": {
"itemCode.keyword": "111"...

**Comment by isoos** [comment]
@mayankjanmejay: I've published 0.1.7 that should handle the hits.total.value response. Could you please open separate issues for the new ones? It is easier to track the separate threads and answer them accordingly.

**Comment by mayankjanmejay** [comment]
Done 
Thank You :)
