### ISSUE TITLE
Prefix Queries

### ISSUE THREAD

**Issue by mayankjanmejay** [isoos/elastic_client#11]
Hello,

 I have a question, using your plug in how can I make a prefix query "prefix": { "itemCode.keyword": "111"...

@mayankjanmejay: I've published 0.1.7 that should handle the hits.total.value response. Could you please open separate issues for the new ones? It is easier to track the separate threads and answer them accordingly.

_Originally posted by @isoos in https://github.com/isoos/elastic_client/issues/10#issuecomment-513173879_

**Comment by mayankjanmejay** [comment]
Could you please add this code your plugin. I have it working locally.

 static Map prefix(String field, String terms) => {
        'prefix': {'$field': terms}
      };

**Comment by isoos** [comment]
Published in 0.1.8

**Comment by mayankjanmejay** [comment]
Would you mind making me a contributor in the project. I am trying to build a custom elastic search widget and I will need to define more queries.

Mayank J.
+971 (55) 963 0008
+40 (799) 468 785
________________________________

**Comment by isoos** [comment]
@mayankjanmejay I accept PRs, feel free to go ahead and make them. One-time contributions will be part of the changelog (similar to [this](https://github.com/agilord/aws_client/blob/master/CHANGELOG.md)), while longer term contributions will of course noted elsewhere too.
