### ISSUE TITLE
Any idea how to use with auth?

### ISSUE THREAD

**Issue by kaumudpa** [isoos/elastic_client#16]
Hey @isoos ,

I am using opendistro with elasticsearch, open distro basic auth is enabled.
To get the response successfully from the server we need to send the request in the following way: `curl -XGET https://<IP Address>:9200 -u userid:password --insecure`

You see additional parameters `-u userid:password --insecure` is always required to get a response. 

any idea how can we do this here?

**Comment by isoos** [comment]
@kaumudpa: basic auth is [just a header](https://en.wikipedia.org/wiki/Basic_access_authentication), e.g. you can [calculate it](https://www.blitter.se/utils/basic-authentication-header-generator/).

If you get the value (and/or the algorithm) from the above links, you can fine-tune the underlying http client to always send the header. It happens to be that we have it in the codebase already:
https://github.com/isoos/elastic_client/blob/master/lib/console_http_transport.dart#L9

**Comment by kaumudpa** [comment]
I will give this a try. Bus how do i add `--insecure` flag with it? 

`--insecure` is used the get the response over https without a valid or demo SSL certificate.

**Comment by isoos** [comment]
@kaumudpa: That part may be need a tweak in the underlying http client, ignoring the bad certificate. I'll need to check the code how you may be doing that the easiest way.

**Comment by isoos** [comment]
@kaumudpa: I've released a new version of `package:http_client` (and also `package:elastic_client`). Could you please try the following: initiate `HttpTransport` with `ConsoleClient(ignoreBadCertificates: true)`. This should take care the bad certificates.

**Comment by kaumudpa** [comment]
@isoos Give me some time, I will post an update here.

**Comment by chetan-cueclad** [comment]
Hi @isoos, Actually i want to execute this curl command : 
curl -XGET https://ip_address:port_number -u username:password --insecure.
So how can we do that by our plugin?

**Comment by kaumudpa** [comment]
@isoos 
Yes, Even i am getting confused on how to build this query! where do i put `ConsoleClient(ignoreBadCertificates: true)` ?

**Comment by isoos** [comment]
Instead of `ConsoleHttpTransport()` you do `HttpTransport(ConsoleClient(ignoreBadCertificates: true), Uri.parse('https://ip:port'), basicAuth: BasicAuth('username', 'password'))`.

Make sure you import the following:
```
import 'package:http_client/console.dart';
import 'package:elastic_client/console_http_transport.dart';
```

**Comment by kaumudpa** [comment]
@isoos The above solution is working perfectly!
