### ISSUE TITLE
Doc type should be optional with the default value `_doc`

### ISSUE THREAD

**Issue by Wikiwix** [isoos/elastic_client#23]
The field `type` in the `search` method (and probably in other places) should be made optional with the default value `_doc`, because of [doc types being deprecated in newer Elasticsearch versions](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html).

**Comment by Wikiwix** [comment]
As Elasticsearch 8 will fail on the use of types, the implementation should probably be better (and more involved -.-) than proposed above.

**Comment by isoos** [comment]
I'm happy to review and accept PRs :)
