### ISSUE TITLE
mergeHeader PR?

### ISSUE THREAD

**Issue by jodinathan** [isoos/elastic_client#4]
Just stumbled upon the merge header error and forked the repo to fix it, however, the code is already fixed.
Maybe it is missing a PR?

**Comment by isoos** [comment]
You mean this one? https://github.com/isoos/elastic_client/pull/3

**Comment by jodinathan** [comment]
I guess so. 
But the pub package is not fixed

**Comment by isoos** [comment]
Right, I've published 0.1.4.
