### ISSUE TITLE
'Client' isn't a function issue

### ISSUE THREAD

**Issue by alexandroheredia** [isoos/elastic_client#43]
![image](https://user-images.githubusercontent.com/64256363/120099642-a4951700-c10a-11eb-9476-d51e871eb979.png)

[class Client, abstract class Client]
The name 'Client' is defined in the libraries 'package:elastic_client/src/elastic_client_impl.dart (via package:elastic_client/elastic_client.dart)' and 'package:http/src/client.dart (via package:http/http.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.dartambiguous_import
'Client' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Client'.dartinvocation_of_non_function

Line taken from: https://github.com/isoos/elastic_client/blob/master/example/example.dart

In my pubspec.yaml I have installed:
  elastic_client: ^0.3.1

some help would be very appreciated!

**Comment by isoos** [comment]
You can specify a library prefix as described in:
https://dart.dev/guides/language/language-tour#using-libraries

e.g. `import 'package:http/http.dart' as http;` and then use `http.Client`.

**Comment by alexandroheredia** [comment]
Thank you for replying so quickly!

Changing to "import 'package:http/http.dart' as http;" fixed it.

Now my problem is a code with no errors but no idea how to implement it with a TextFormField. I know there's an example file with the logic, but us noobs don't know how to apply that logic.
