### ISSUE TITLE
How to combine multiple query into one???

### ISSUE THREAD

**Issue by vivekaion** [isoos/elastic_client#53]
**My user search
"the avenger infinity war"**

so I need complex query in three part
**Part 1:** importance 1.5
		phrase search : "the avenger infinity war"

**PArt 2:** importance 1.0
		Word search "the" and "avenger" and "infinity" and "war"
		
**PArt 3:** importance 0.5
        Fuzzy search		
		"the"~0.5 and 
		"avenger"~0.5 and 
		"infinity"~0.5 and 
		"war"~0.5
		
	combining this search to one. well I am willing to contribute if you show me some way to build this, in string version i can made this, but don't know how to build in Map<dynamic, dynamic>
	
	is there any way, just a small hint will also be much helpful.

even just a small reference of code how to combine multiple query into one would be helpful, and in response I am happy to share my final search query builder code. I did same with lucene.net desktop version with much more complex query, I am trying to do same here, and I am sure that this will help many other fellow programmers.

**Comment by vivekaion** [comment]
Or can you just give us some way where we can build query into string version and pass that to client? like I do all string manipulation and I just pass final query string to client library. ???

**Comment by isoos** [comment]
Query preprocessing is outside of the scope of this client. Once you have the processed query, the bool query's `should` clause will be able to do what you are looking for:
https://pub.dev/documentation/elastic_client/latest/elastic_client/Query/bool.html
More info here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by vivekaion** [comment]
thank you so much. appreciated the help.

please keep up the good work. it helped me a lot. sincere thanks from a
fellow developer.
