### ISSUE TITLE
Phrase suggestion not working on DART elastic_client ?

### ISSUE THREAD

**Issue by Vi-cs** [isoos/elastic_client#60]
Hi,

I am trying to get phrases suggestions on my Flutter app using client.search() from https://pub.dev/packages/elastic_client

Works fine on REST API :
`{
  "suggest":{
  	"text": "Britih",
	"content": {
		"phrase": {
			"field": "content",
			"highlight": {
				"pre_tag": "<em>", 
				"post_tag": "</em>"
				}
				}
				}
				}
  
}`

However, when I replicate this request on dart/Flutter, I get the following error:  
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'int' in type cast
#0      Client.search.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:elastic_client/src/_client.dart:331:29)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)`

It seems to me that in _client.dart, frequency is expected but elastic return none. 

```
return SuggestHitOption(
            m['text'] as String,
            m['score'] as double,
            freq: m['freq'] as int, <== ligne 331
            highlighted: m['highlighted'] as String,
          );
```

**Comment by isoos** [comment]
Thanks for reporting this. It looks like an easy fix to make it optional... would you be interested in a PR?

**Comment by isoos** [comment]
(Or rather always-returning 0 or -1 as a frequency when it is not present)

**Comment by Vi-cs** [comment]
Yes :) thanks


Le lun. 18 avr. 2022, 14:46, István Soós ***@***.***> a
écrit :

**Comment by Vi-cs** [comment]
Thanks Istvan
