### ISSUE TITLE
Term Enum Support 

### ISSUE THREAD

**Issue by Vi-cs** [isoos/elastic_client#62]
Hi, 
It seems that term_enum_ API is not supported. Is there any plan to support it in a near future ?
https://www.elastic.co/guide/en/elasticsearch/reference/8.1/search-terms-enum.html
Best,

**Comment by isoos** [comment]
I'm happy to review and merge PRs :)
It should be easy to follow the same patterns as other APIs already established.

**Comment by Vi-cs** [comment]
great, I'll try

Le mer. 20 avr. 2022, 20:19, István Soós ***@***.***> a
écrit :
