### ISSUE TITLE
ssl certificate

### ISSUE THREAD

**Issue by Oumayma-laaj** [isoos/elastic_client#64]
good day everyone, I'm doing end of study project
is there a way to authenticate elastic_client using self signed certificate (pem)

**Comment by isoos** [comment]
IIRC it is not supported by the Dart SDK (yet), nor by any of the largest http client packages - but I may be wrong here. Until it is not supported in either of these, I don't think this package will support it on its own.

**Comment by Oumayma-laaj** [comment]
thanks for responding I just disable http ssl from elasticsearch and used ApiKey instead for authorization
