### ISSUE TITLE
Null _score value causing issues with Flutter 3.13.4

### ISSUE THREAD

**Issue by gvisniuc** [isoos/elastic_client#67]
Hi there,

I've recently upgraded flutter to 3.13.4 and began work on null safety.

In some cases, for example `top_hits` aggregations, the `_score` key is missing from the `hits` causing an error when casting the null value to double.

https://github.com/isoos/elastic_client/blob/master/lib/src/elastic_client_impl.dart#L147C15-L147C46

Fixed it for now with `score: map['_score'] != null ? map['_score'] as double : 0.0,` but there might be a better solution of course.

**Comment by isoos** [comment]
@gvisniuc: Would you mind filing a PR? please add a changelog entry for it and bump version too.

**Comment by gvisniuc** [comment]
hey @isoos more than happy to https://github.com/isoos/elastic_client/pull/68
