### ISSUE TITLE
Change "_source" logic in Client.search() method

### ISSUE THREAD

**Issue by olachris** [isoos/elastic_client#7]
Hi, thanks for this Elasticsearch client! 

I would like to be able to use source filtering as per https://www.elastic.co/guide/en/elasticsearch/reference/7.2/search-request-source-filtering.html. 

This doesnt work at the moment because in the Client.search() method in elastic_client_impl.dart "_source" is always set as a bool. Elasticsearch allows this to be a boolean, a string or a list of strings (I need the latter).

To make this possible i would like to make the following changes:
- Add a param 'source' with type dynamic to the search() method
- if that has a value then use it as "_source"
- if it does not have a value then set it to true or false based on the fetchSource param

(Note that the fetchSource param is only kept to ensure this is a backwards compatible change. If you are not concerned with keeping backwards compatibility then the change can simply be:
- Rename fetchSource param to source, and change its type from bool to dynamic)
 
Would you accept a PR that makes those changes?:

**Comment by isoos** [comment]
Sure, thanks for the suggestions! I'd like to ask you to:
- mark `fetchSource` deprecated, but keep it around
- introduce `source` as you've described, handle fetchSource if it is present
- add a changelog about it

This way it is not an immediately breaking, but introduces a migration path, and also a potential cleanup for the next larger release.

**Comment by olachris** [comment]
Thanks for the quick response, i have created the PR as discussed 👍
